services:
  backend:
    build: ./
    container_name: backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: /bin/sh run.sh
    volumes:
      - ./app:/app
    ports:
      - 80:8000

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    volumes:
      - data:/var/lib/postgresql/data/

volumes:
  data:
